version: "3"
services:
  jupyter:
    build: .  # build contexts
    volumes:
      - $PWD:/work/
    ports:
      - 8888:8888
    tty: True
    stdin_open: True 
    # hostname: Docker5046
    # container_name: ubuntu18
    # command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
