globals:
  seed: 5046
  device: cuda
  num_epochs: 50
  output_dir: output/000_ResNet50
  main_metric: epoch_f1
  minimize_metric: False
  input_key: image
  input_target_key: targets
  weights:
  folds:
    - 0  # cvの際、0のみ行う(つまり1-fold cv)

data:
  train_skip: ../input/birdsong-recognition/skipped.txt
  train_df_path: ../input/birdsong-recognition/train.csv
  train_audio_path: ../input/birdsong-recognition/train_audio_resampled
  train_resample_audio_path: 
    - ../input/birdsong-resampled-train-audio-00
    - ../input/birdsong-resampled-train-audio-01
    - ../input/birdsong-resampled-train-audio-02
    - ../input/birdsong-resampled-train-audio-03
    - ../input/birdsong-resampled-train-audio-04
  test_df_path: ../input/birdsong-recognition/test.csv
  test_audio_path: ../input/birdsong-recognition/test_audio

dataset:
  name: SpectrogramDataset
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: ResNetLoss
  params:
    loss_type: bce

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet50
  params:
    pretrained: True
    n_classes: 264

loader:
  train:
    batch_size: 50
    shuffle: True
    num_workers: 2
  valid:
    batch_size: 100
    shuffle: False
    num_workers: 2

callbacks:
  - name: F1Callback
    params:
      input_key: targets
      output_key: logits
      model_output_key: multilabel_proba
      prefix: f1
  - name: mAPCallback
    params:
      input_key: targets
      output_key: logits
      model_output_key: multilabel_proba
      prefix: mAP