globals:
  seed: 5046
  device: cuda
  num_epochs: 50
  output_dir: output/001_panns
  main_metric: epoch_f1
  minimize_metric: False
  input_key: waveform
  input_target_key: targets
  weights: "../input/birdcall-resnet50-init-weights/best.pth"
  folds:
    - 0  # cvの際、0のみ行う(つまり1-fold cv)

data:
  train_skip: ../input/birdsong-recognition/skipped.txt
  train_df_path: ../input/birdsong-recognition/train.csv
  train_audio_path: ../input/birdsong-recognition/train_audio_resampled
  # train_audio_path: ../input/birdsong-recognition/train_audio
  train_resample_audio_path: 
    - ../input/birdsong-resampled-train-audio-00
    - ../input/birdsong-resampled-train-audio-01
    - ../input/birdsong-resampled-train-audio-02
    - ../input/birdsong-resampled-train-audio-03
    - ../input/birdsong-resampled-train-audio-04
  test_df_path: ../input/birdcall-check/test.csv
  test_audio_path: ../input/birdcall-check/test_audio
  sub: ../input/birdsong-recognition/sample_submission.csv

dataset:
  name: PANNsDataset
  params: 
    addnoise_p: 0.3
    denoise_p: 0.1

loss:
  name: PANNsLoss
  params:
    loss_type: bce

optimizer:
  name: Adam
  params:
    lr: 0.005

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: pannscnn
  params:
    sample_rate: 32000
    window_size: 1024
    hop_size: 320
    mel_bins: 64
    fmin: 50
    fmax: 14000
    classes_num: 512

loader:
  train:
    batch_size: 50
    shuffle: True
    num_workers: 2
    pin_memory: True
    drop_last: True
  valid:
    batch_size: 100
    shuffle: False
    num_workers: 2
    pin_memory: True
    drop_last: False

callbacks:
  - name: F1Callback
    params:
      input_key: targets
      output_key: logits
      model_output_key: multilabel_proba
      prefix: f1
  - name: mAPCallback
    params:
      input_key: targets
      output_key: logits
      model_output_key: multilabel_proba
      prefix: mAP
  - name: CheckpointCallback
    params:
      save_n_best: 0

transforms:
  horizontal_flip: 
    p: 0.5
  cutout: 
    p: 0.0
  mixup: 
    P: 0.0
  spec_augment:
    p: 0.3
    num_mask: 2
    freq_masking_max_percentage: 0.15
    time_masking_max_percentage: 0.3
